import os

class Config:
    DEBUG = os.environ.get('FLASK_ENV') != 'production'
    SECRET_KEY = os.environ.get('SECRET_KEY', 'super-secret-key')
    
    # Use PostgreSQL on Heroku, SQLite locally
    if os.environ.get('DATABASE_URL'):
        SQLALCHEMY_DATABASE_URI = os.environ.get('DATABASE_URL').replace('postgres://', 'postgresql://')
    else:
        SQLALCHEMY_DATABASE_URI = 'sqlite:///jobs.db'
    
    JOB_SCRAPE_INTERVAL_HOURS = 6  # Scrape every 6 hours

    # Master list of all companies to monitor (deduplicated, standardized)
    FAVORITE_COMPANIES = [
        'Retool', 'Nextdoor', 'Duolingo', 'Viral Nation', 'Bond Brand Loyalty',
        'StackAdapt', 'Index Exchange', 'OpenText', 'Barnacle Systems Inc.', 'Chime',
        'Boosted.ai', 'Coda', 'Top Hat', 'Hightouch', 'Intelliculture', 'OpsLevel',
        'Otter.ai', 'CircleCI', 'Flywheel Digital', 'NURO', 'Trellis', 'Retailogists',
        'Adaptivist', 'Ledn', 'RouteThis', 'BIMM', 'Ziphq', 'Wish', 'SkipTheDishes',
        'TouchBistro', 'Thoughtworks', 'Etsy', 'Cloudflare', 'Chainalysis', 'Binance',
        'Webtoon Entertainment', 'Wave', 'Rogers', 'Loop Financial', 'Prodigy Education',
        'Clearco', 'Archon Systems Inc.', 'Plenty of Fish', 'Venngage', 'Ritual.co',
        'Swoon', 'Zillow', 'Coinbase', 'Wayfair', 'Okta', 'Faire', 'Instacart',
        'Stripe', 'Reddit', 'Airbnb', 'Uber', 'Bluedot', 'Rippling', 'Cohere',
        'Clutch', 'Dapper Labs', 'Outschool', 'Bolt', 'Upgrade', 'Lyft', 'Lookout',
        'ApplyBoard', 'Dialpad', 'Addepar', 'Hopper', 'Notch', 'VTS', 'Cockroach Labs',
        'Hyperscience', 'Rivian', 'ChargePoint', 'LinkedIn', 'Tonal', 'GlossGenius',
        'Square', 'Unether AI', 'Copado', 'EvenUp', 'Super.com', 'BenchSci', 'Benevity',
        'Vena Solutions', 'Vagaro', 'Fabric.inc', 'Procurify', 'App Annie', 'Tenstorrent',
        'Forethought', 'Course Hero', 'League', 'Chegg', 'AI Redefined', 'Mistplay',
        'Moves Financial', 'Grammarly', 'Replit', 'Replicant', 'Plooto', 'Fullscript',
        'Rose Rocket', 'Validere', 'Certn', 'Coffee Meets Bagel', 'Mattermost',
        'AuditBoard', 'Pachyderm', 'Sanctuary AI', 'Unity', 'GoDaddy',
        'CentralSquare Technologies', 'Yelp', 'NODA', 'CentML', 'Remarcable Inc.',
        'SAGE', 'X', 'Tesla', 'TMX Group', 'Nvidia', 'Arctic Wolf', 'Nokia', 'AMD',
        'Vopemed', 'Flashfood', 'Gusto', 'Epic Games', 'Cribl', 'Slack', 'Indigo',
        'Auvik Networks', 'SOTI', 'KeyDataCyber', 'Opifiny Corp', 'Meta', 'Tomato Pay Inc',
        'Bitsight', 'Spotify', 'EA', 'Workiva', 'The Trade Desk', 'Robinhood',
        'Intelliware', 'Figma', 'Verkada', 'Schonfeld', 'Ecomtent', 'Citrus (Camp Management Software)',
        'TalentMinded', 'Transify', 'Sync.com', 'Questrade', 'Xanadu', 'Demonware',
        'Shyft Labs', 'Wealthsimple', 'Infor', 'Connor, Clark & Lunn Infrastructure',
        'FGS Global', 'Lancey', 'Google', 'Amazon', 'Netflix', 'Snapchat', 'Twilio'
    ]

    # Keywords for job filtering (broadened)
    KEYWORDS = [
        "intern", "internship", "co-op", "student", 
        "new grad", "entry level", "software", "developer",
        "engineer", "2026", "2027", "sde", "swe"
    ]

    # Updated job sources (sorted by date)
    # Updated job sources with **raw GitHub URL** for internships markdown
    SOURCES = {
        "github": "https://raw.githubusercontent.com/vanshb03/Summer2026-Internships/dev/README.md",
        "indeed": "https://www.indeed.com/jobs?q=internship&l=&sort=date",
        "glassdoor": "https://www.glassdoor.ca/Job/software-engineer-intern-jobs-SRCH_KO0,24.htm?sortBy=date_desc",
        "builtin": "https://builtintoronto.com/jobs?search=intern&sort=newest"
    }

    # Auto-answers for application questions
    AUTO_ANSWERS = {
        "authorized to work": "Yes",
        "work authorization": "Yes",
        "visa sponsorship": "No",
        "legally eligible": "Yes",
        "require sponsorship": "No",
        "work eligibility": "Authorized",
        "will you now or in the future require sponsorship": "No",
        "are you legally authorized to work": "Yes"
    }

    # Career pages for each company (fully matched to frontend)
    COMPANY_CAREER_PAGES = {
        'Retool': 'https://retool.com/careers',
        'Nextdoor': 'https://about.nextdoor.com/careers/',
        'Duolingo': 'https://careers.duolingo.com/',
        'Viral Nation': 'https://www.viralnation.com/careers/',
        'Bond Brand Loyalty': 'https://www.bondbrandloyalty.com/about/careers/',
        'StackAdapt': 'https://www.stackadapt.com/careers',
        'Index Exchange': 'https://www.indexexchange.com/careers/',
        'OpenText': 'https://careers.opentext.com/',
        'Barnacle Systems Inc.': 'https://www.barnacle.io/pages/careers',
        'Chime': 'https://www.chime.com/careers/',
        'Boosted.ai': 'https://boosted.ai/careers/',
        'Coda': 'https://coda.io/careers',
        'Top Hat': 'https://tophat.com/company/careers/',
        'Hightouch': 'https://hightouch.com/careers',
        'Intelliculture': 'https://intelliculture.com/careers',
        'OpsLevel': 'https://www.opslevel.com/careers',
        'Otter.ai': 'https://otter.ai/careers',
        'CircleCI': 'https://circleci.com/careers',
        'Flywheel Digital': 'https://flywheeldigital.com/careers',
        'NURO': 'https://nuro.ai/careers',
        'Trellis': 'https://www.trellis.org/careers',
        'Retailogists': 'https://www.retailogists.com/careers',
        'Adaptivist': 'https://www.adaptavist.com/careers',
        'Ledn': 'https://ledn.io/careers',
        'RouteThis': 'https://routethis.com/careers',
        'BIMM': 'https://www.bimm.com/careers',
        'Ziphq': 'https://ziphq.com/careers',
        'Wish': 'https://www.wish.com/careers',
        'SkipTheDishes': 'https://www.skipthedishes.com/about/careers',
        'TouchBistro': 'https://www.touchbistro.com/careers/',
        'Thoughtworks': 'https://www.thoughtworks.com/careers',
        'Etsy': 'https://www.etsy.com/careers',
        'Cloudflare': 'https://www.cloudflare.com/careers/',
        'Chainalysis': 'https://www.chainalysis.com/careers/',
        'Binance': 'https://www.binance.com/en/careers',
        'Webtoon Entertainment': 'https://careers.webtoons.com/',
        'Wave': 'https://www.waveapps.com/careers',
        'Rogers': 'https://jobs.rogers.com/',
        'Loop Financial': 'https://www.bankonloop.com/en-ca/careers',
        'Prodigy Education': 'https://www.prodigygame.com/main-en/careers/',
        'Clearco': 'https://clear.co/careers',
        'Archon Systems Inc.': 'https://www.archonsystems.com/careers',
        'Plenty of Fish': 'https://www.pof.com/careers',
        'Venngage': 'https://venngage.com/careers',
        'Ritual.co': 'https://ritual.co/careers',
        'Swoon': 'https://swoonstaffing.com/careers/',
        'Zillow': 'https://www.zillowgroup.com/careers/',
        'Coinbase': 'https://www.coinbase.com/careers',
        'Wayfair': 'https://www.aboutwayfair.com/careers',
        'Okta': 'https://www.okta.com/company/careers/',
        'Faire': 'https://www.faire.com/careers',
        'Instacart': 'https://careers.instacart.com/',
        'Stripe': 'https://stripe.com/jobs',
        'Reddit': 'https://www.redditinc.com/careers',
        'Airbnb': 'https://careers.airbnb.com/',
        'Uber': 'https://www.uber.com/careers/',
        'Bluedot': 'https://bluedot.io/careers',
        'Rippling': 'https://www.rippling.com/careers',
        'Cohere': 'https://cohere.com/careers',
        'Clutch': 'https://clutch.com/careers',
        'Dapper Labs': 'https://www.dapperlabs.com/careers',
        'Outschool': 'https://outschool.com/careers',
        'Bolt': 'https://www.bolt.com/careers',
        'Upgrade': 'https://www.upgrade.com/careers',
        'Lyft': 'https://www.lyft.com/careers',
        'Lookout': 'https://www.lookout.com/company/careers',
        'ApplyBoard': 'https://www.applyboard.com/careers',
        'Dialpad': 'https://www.dialpad.com/careers',
        'Addepar': 'https://addepar.com/careers',
        'Hopper': 'https://www.hopper.com/careers',
        'Notch': 'https://notch.com/careers',
        'VTS': 'https://www.vts.com/careers',
        'Cockroach Labs': 'https://www.cockroachlabs.com/careers/',
        'Hyperscience': 'https://www.hyperscience.com/careers/',
        'Rivian': 'https://rivian.com/careers',
        'ChargePoint': 'https://www.chargepoint.com/about/careers',
        'LinkedIn': 'https://careers.linkedin.com/',
        'Tonal': 'https://www.tonal.com/careers',
        'GlossGenius': 'https://glossgenius.com/careers',
        'Square': 'https://squareup.com/us/en/careers',
        'Unether AI': '',
        'Copado': 'https://www.copado.com/company/careers',
        'EvenUp': 'https://evenup.com/careers',
        'Super.com': 'https://super.com/careers',
        'BenchSci': 'https://www.benchsci.com/careers',
        'Benevity': 'https://benevity.com/careers',
        'Vena Solutions': 'https://www.venasolutions.com/careers',
        'Vagaro': 'https://www.vagaro.com/careers',
        'Fabric.inc': 'https://fabric.inc/careers',
        'Procurify': 'https://www.procurify.com/careers',
        'App Annie': 'https://www.data.ai/en/company/careers/',
        'Tenstorrent': 'https://www.tenstorrent.com/careers',
        'Forethought': 'https://forethought.ai/careers',
        'Course Hero': 'https://www.coursehero.com/jobs/',
        'League': 'https://league.com/careers',
        'Chegg': 'https://www.chegg.com/about/working-at-chegg',
        'AI Redefined': 'https://ai-r.com/careers',
        'Mistplay': 'https://www.mistplay.com/careers',
        'Moves Financial': 'https://www.movesfinancial.com/careers',
        'Grammarly': 'https://www.grammarly.com/jobs',
        'Replit': 'https://replit.com/careers',
        'Replicant': 'https://www.replicant.ai/careers',
        'Plooto': 'https://www.plooto.com/careers',
        'Fullscript': 'https://fullscript.com/careers',
        'Rose Rocket': 'https://www.roserocket.com/careers',
        'Validere': 'https://validere.com/careers',
        'Certn': 'https://certn.co/careers',
        'Coffee Meets Bagel': 'https://coffeemeetsbagel.com/careers',
        'Mattermost': 'https://mattermost.com/careers/',
        'AuditBoard': 'https://www.auditboard.com/company/careers/',
        'Pachyderm': 'https://www.pachyderm.com/careers',
        'Sanctuary AI': 'https://www.sanctuary.ai/careers',
        'Unity': 'https://careers.unity.com/',
        'GoDaddy': 'https://careers.godaddy.com/',
        'CentralSquare Technologies': 'https://www.centralsquare.com/about/careers',
        'Yelp': 'https://www.yelp.careers/us/en',
        'NODA': '',
        'CentML': 'https://centml.ai/careers',
        'Remarcable Inc.': 'https://remarcable-inc.careerplug.com/jobs',
        'SAGE': 'https://www.sage.com/en-gb/company/careers/',
        'X': 'https://x.com/careers',
        'Tesla': 'https://www.tesla.com/careers',
        'TMX Group': 'https://www.tmx.com/about/careers',
        'Nvidia': 'https://www.nvidia.com/en-us/about-nvidia/careers/',
        'Arctic Wolf': 'https://arcticwolf.com/company/careers/',
        'Nokia': 'https://www.nokia.com/about-us/careers/',
        'AMD': 'https://www.amd.com/en/corporate/careers',
        'Vopemed': '',
        'Flashfood': 'https://www.flashfood.com/careers',
        'Gusto': 'https://gusto.com/about/careers',
        'Epic Games': 'https://www.epicgames.com/site/en-US/careers',
        'Cribl': 'https://cribl.io/company/careers/',
        'Slack': 'https://slack.com/careers',
        'Indigo': 'https://careers.indigo.ca/',
        'Auvik Networks': 'https://www.auvik.com/about-us/careers/',
        'SOTI': 'https://www.soti.net/careers/',
        'KeyDataCyber': 'https://keydatacyber.com/careers',
        'Opifiny Corp': 'https://opifiny.com/careers',
        'Meta': 'https://www.metacareers.com/',
        'Tomato Pay Inc': 'https://apply.workable.com/tomato-pay/?lng=en',
        'Bitsight': 'https://www.bitsight.com/company/careers',
        'Spotify': 'https://www.spotifyjobs.com/',
        'Electronic Arts': 'https://jobs.ea.com/en_US/careers/Home/Toronto?listFilterMode=1',
        'Workiva': 'https://www.workiva.com/careers',
        'The Trade Desk': 'https://www.thetradedesk.com/careers',
        'Robinhood': 'https://careers.robinhood.com/',
        'Intelliware': 'https://www.intelliware.com/careers/',
        'Figma': 'https://www.figma.com/careers/',
        'Verkada': 'https://www.verkada.com/careers/',
        'Schonfeld': 'https://www.schonfeld.com/careers',
        'Ecomtent': 'https://ecomtent.zohorecruit.ca/jobs/Careers',
        'Citrus (Camp Management Software)': 'https://www.joincitrus.com/join-our-team',
        'TalentMinded': 'https://www.talentminded.ca/careers',
        'Transify': 'https://www.transify.com/careers',
        'Sync.com': 'https://www.sync.com/careers',
        'Questrade': 'https://www.questrade.com/careers',
        'Xanadu': 'https://www.xanadu.ai/careers',
        'Demonware': 'https://demonware.net/careers',
        'Shyft Labs': 'https://shyftlabs.io/careers',
        'Wealthsimple': 'https://www.wealthsimple.com/en-ca/careers',
        'Infor': 'https://www.infor.com/about/careers',
        'Connor, Clark & Lunn Infrastructure': 'https://cclinfrastructure.com/careers',
        'FGS Global': 'https://fgsglobal.com/careers',
        'Lancey': 'https://www.ycombinator.com/companies/lancey/jobs',
        'Google': 'https://careers.google.com/jobs/',
        'Amazon': 'https://www.amazon.jobs/',
        'Netflix': 'https://jobs.netflix.com/',
        'Snapchat': 'https://snap.com/en-US/jobs',
        'Twilio': 'https://www.twilio.com/company/jobs',
    }

# Singleton config instance
config = Config()